/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcu;

/**
 *
 * @author MD:Ismail Hosen Raj
 */
public class cal extends javax.swing.JFrame {

    /**
     * Creates new form cal
     */
    char ch;
    public cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B_dot = new javax.swing.JButton();
        B_equal = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        B_plus = new javax.swing.JButton();
        B_sub = new javax.swing.JButton();
        B_div = new javax.swing.JButton();
        B_mul = new javax.swing.JButton();
        B_Ac = new javax.swing.JButton();
        B_DEL1 = new javax.swing.JButton();
        B_pow = new javax.swing.JButton();
        B_square = new javax.swing.JButton();
        B_suare3 = new javax.swing.JButton();
        B_cos = new javax.swing.JButton();
        B_sin1 = new javax.swing.JButton();
        B_log = new javax.swing.JButton();
        B_binary = new javax.swing.JButton();
        B_hex = new javax.swing.JButton();
        B_tan1 = new javax.swing.JButton();
        B_octal = new javax.swing.JButton();
        B_pi = new javax.swing.JButton();
        B_cbrt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        B1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B_dot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_dot.setText(".");
        B_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_dotActionPerformed(evt);
            }
        });

        B_equal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_equal.setText("=");
        B_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_equalActionPerformed(evt);
            }
        });

        B0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B0.setText("0");
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });

        B_plus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_plus.setText("+");
        B_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_plusActionPerformed(evt);
            }
        });

        B_sub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_sub.setText("-");
        B_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_subActionPerformed(evt);
            }
        });

        B_div.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_div.setText("/");
        B_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_divActionPerformed(evt);
            }
        });

        B_mul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_mul.setText("*");
        B_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_mulActionPerformed(evt);
            }
        });

        B_Ac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_Ac.setText("AC");
        B_Ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AcActionPerformed(evt);
            }
        });

        B_DEL1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_DEL1.setText("DEL");
        B_DEL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DEL1ActionPerformed(evt);
            }
        });

        B_pow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_pow.setText("x^2");
        B_pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_powActionPerformed(evt);
            }
        });

        B_square.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_square.setText("Root");
        B_square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_squareActionPerformed(evt);
            }
        });

        B_suare3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_suare3.setText("x^3");
        B_suare3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_suare3ActionPerformed(evt);
            }
        });

        B_cos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_cos.setText("cos");
        B_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cosActionPerformed(evt);
            }
        });

        B_sin1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_sin1.setText("sin");
        B_sin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_sin1ActionPerformed(evt);
            }
        });

        B_log.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_log.setText("log");
        B_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_logActionPerformed(evt);
            }
        });

        B_binary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_binary.setText("BIN");
        B_binary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_binaryActionPerformed(evt);
            }
        });

        B_hex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_hex.setText("HEX");
        B_hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_hexActionPerformed(evt);
            }
        });

        B_tan1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_tan1.setText("tan");
        B_tan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_tan1ActionPerformed(evt);
            }
        });

        B_octal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_octal.setText("OCT");
        B_octal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_octalActionPerformed(evt);
            }
        });

        B_pi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_pi.setText("Pi");
        B_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_piActionPerformed(evt);
            }
        });

        B_cbrt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_cbrt.setText("cbrt");
        B_cbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cbrtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B_div, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(B_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B_pow, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_Ac, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_DEL1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_square, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B_suare3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_sin1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_tan1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B_cbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_octal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_binary, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B_hex, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_log, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_DEL1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Ac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_pow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_square, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_suare3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_sin1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_log, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_tan1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_hex, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_binary, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_octal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_cbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B1.getText();
        display.setText(a);
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B2.getText();
        display.setText(a);
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B3.getText();
        display.setText(a);
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B4.getText();
        display.setText(a);
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B5.getText();
        display.setText(a);
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B6.getText();
        display.setText(a);
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B7.getText();
        display.setText(a);
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B8.getText();
        display.setText(a);
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B9.getText();
        display.setText(a);
    }//GEN-LAST:event_B9ActionPerformed

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
        // TODO add your handling code here:
        String a = display.getText()+B0.getText();
        display.setText(a);
    }//GEN-LAST:event_B0ActionPerformed

    private void B_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_dotActionPerformed
        // TODO add your handling code here:
        String check = display.getText();
        if(check.charAt(check.length()-1)!='.')
        {
            if(check.indexOf('.')==-1){
                String a = display.getText()+B_dot.getText();
                display.setText(a);
            }
        }
    }//GEN-LAST:event_B_dotActionPerformed

    private void B_AcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AcActionPerformed
        // TODO add your handling code here:
        display.setText("");
    }//GEN-LAST:event_B_AcActionPerformed

    private void B_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_plusActionPerformed
        // TODO add your handling code here:
        String check = display.getText();
        if(check.charAt(check.length()-1)!='+' && check.charAt(check.length()-1)!='-' && check.charAt(check.length()-1)!='*' && check.charAt(check.length()-1)!='/' )
        {
            if(check.indexOf('+')==-1){
                String a = display.getText()+B_plus.getText();
                display.setText(a);
                ch = '+';
            }
        }
    }//GEN-LAST:event_B_plusActionPerformed

    private void B_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_subActionPerformed
        // TODO add your handling code here:
        String check = display.getText();
        if(check.charAt(check.length()-1)!='+' && check.charAt(check.length()-1)!='-' && check.charAt(check.length()-1)!='*' && check.charAt(check.length()-1)!='/' )
        {
            if(check.indexOf('-')==-1){
                String a = display.getText()+B_sub.getText();
                display.setText(a);
                ch = '-';
            }
        }
    }//GEN-LAST:event_B_subActionPerformed

    private void B_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_mulActionPerformed
        // TODO add your handling code here:
       String check = display.getText();
       if(check.charAt(check.length()-1)!='+' && check.charAt(check.length()-1)!='-' && check.charAt(check.length()-1)!='*' && check.charAt(check.length()-1)!='/' )
        {
            if(check.indexOf('*')==-1){
                String a = display.getText()+B_mul.getText();
                display.setText(a);
                ch = '*';
            }
        }
    }//GEN-LAST:event_B_mulActionPerformed

    private void B_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_divActionPerformed
        // TODO add your handling code here:
        String check = display.getText();
        if(check.charAt(check.length()-1)!='+' && check.charAt(check.length()-1)!='-' && check.charAt(check.length()-1)!='*' && check.charAt(check.length()-1)!='/' )
        {
            if(check.indexOf('/')==-1){
                String a = display.getText()+B_div.getText();
                display.setText(a);
                ch = '/';
            }
        }
    }//GEN-LAST:event_B_divActionPerformed

    private void B_DEL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DEL1ActionPerformed
        // TODO add your handling code here:
        String a = display.getText();
        a = a.substring(0,a.length()-1);
        display.setText(a);
    }//GEN-LAST:event_B_DEL1ActionPerformed

    private void B_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_equalActionPerformed
        // TODO add your handling code here:
        String a = display.getText();
        String []b = a.split("[/*+-]");
        double num1 = Double.parseDouble(b[0]);
        double num2 = Double.parseDouble(b[1]);
        double sum = 0;
        if(ch == '+')
        {
            sum = num1 + num2;
        }
        else if (ch == '-')
        {
            sum = num1 - num2;
        }
        else if (ch == '*')
        {
            sum = num1 * num2;
        }
        else if (ch == '/')
        {
            if(num2!=0){
                sum = num1 / num2;
            }
            
        }
        String result = Double.toString(sum);
        display.setText(a+"="+result);
     
    }//GEN-LAST:event_B_equalActionPerformed

    private void B_powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_powActionPerformed
        // TODO add your handling code here:
        String hi = display.getText();
        if(hi.indexOf('+')==-1 && hi.indexOf('-')==-1 && hi.indexOf('/')==-1 && hi.indexOf('*')==-1)
        {
            double sum = Double.parseDouble(hi);
            double sum1 = sum*sum;
             String sum2 = Double.toString(sum1);
             display.setText(sum2);
        }
    }//GEN-LAST:event_B_powActionPerformed

    private void B_squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_squareActionPerformed
        // TODO add your handling code here:
        String hi = display.getText();
        if(hi.indexOf('+')==-1 && hi.indexOf('-')==-1 && hi.indexOf('/')==-1 && hi.indexOf('*')==-1)
        {
            double sum = Double.parseDouble(hi);
            double sum1 = Math.sqrt(sum);
             String sum2 = Double.toString(sum1);
             display.setText(sum2);
        }
    }//GEN-LAST:event_B_squareActionPerformed

    private void B_suare3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_suare3ActionPerformed
        // TODO add your handling code here:
         String hi = display.getText();
        if(hi.indexOf('+')==-1 && hi.indexOf('-')==-1 && hi.indexOf('/')==-1 && hi.indexOf('*')==-1)
        {
            double sum = Double.parseDouble(hi);
            double sum1 = sum*sum*sum;
             String sum2 = Double.toString(sum1);
             display.setText(sum2);
        }
    }//GEN-LAST:event_B_suare3ActionPerformed

    private void B_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cosActionPerformed
        // TODO add your handling code here:
         String hi = display.getText();
        if(hi.indexOf('+')==-1 && hi.indexOf('-')==-1 && hi.indexOf('/')==-1 && hi.indexOf('*')==-1)
        {
            double sum = Double.parseDouble(hi);
            double sum1 = Math.cos(sum);
             String sum2 = Double.toString(sum1);
             display.setText(sum2);
        }
    }//GEN-LAST:event_B_cosActionPerformed

    private void B_sin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_sin1ActionPerformed
        // TODO add your handling code here:
           String hi = display.getText();
        if(hi.indexOf('+')==-1 && hi.indexOf('-')==-1 && hi.indexOf('/')==-1 && hi.indexOf('*')==-1)
        {
            double sum = Double.parseDouble(hi);
            double sum1 = Math.sin(sum);
             String sum2 = Double.toString(sum1);
             display.setText(sum2);
        }
    }//GEN-LAST:event_B_sin1ActionPerformed

    private void B_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_logActionPerformed
        // TODO add your handling code here:
           String hi = display.getText();
        if(hi.indexOf('+')==-1 && hi.indexOf('-')==-1 && hi.indexOf('/')==-1 && hi.indexOf('*')==-1)
        {
            double sum = Double.parseDouble(hi);
            double sum1 = Math.log(sum);
             String sum2 = Double.toString(sum1);
             display.setText(sum2);
        }
    }//GEN-LAST:event_B_logActionPerformed

    private void B_binaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_binaryActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(display.getText());
        display.setText(Integer.toString(a,2));
        
    }//GEN-LAST:event_B_binaryActionPerformed

    private void B_hexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_hexActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(display.getText());
        display.setText(Integer.toString(a,16));
    }//GEN-LAST:event_B_hexActionPerformed

    private void B_tan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_tan1ActionPerformed
        // TODO add your handling code here:
           String hi = display.getText();
        if(hi.indexOf('+')==-1 && hi.indexOf('-')==-1 && hi.indexOf('/')==-1 && hi.indexOf('*')==-1)
        {
            double sum = Double.parseDouble(hi);
            double sum1 = Math.tan(sum);
             String sum2 = Double.toString(sum1);
             display.setText(sum2);
        }
    }//GEN-LAST:event_B_tan1ActionPerformed

    private void B_octalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_octalActionPerformed
        // TODO add your handling code here:
         int a = Integer.parseInt(display.getText());
        display.setText(Integer.toString(a,8));
    }//GEN-LAST:event_B_octalActionPerformed

    private void B_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_piActionPerformed
        // TODO add your handling code here:
        Double pos;
        pos = (3.141592653589793);
        display.setText(Double.toString(pos));
    }//GEN-LAST:event_B_piActionPerformed

    private void B_cbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cbrtActionPerformed
        // TODO add your handling code here:
            String hi = display.getText();
        if(hi.indexOf('+')==-1 && hi.indexOf('-')==-1 && hi.indexOf('/')==-1 && hi.indexOf('*')==-1)
        {
            double sum = Double.parseDouble(hi);
            double sum1 = Math.cbrt(sum);
            //double sum2 = Math.
             String sum2 = Double.toString(sum1);
             display.setText(sum2);
        }
    }//GEN-LAST:event_B_cbrtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton B_Ac;
    private javax.swing.JButton B_DEL1;
    private javax.swing.JButton B_binary;
    private javax.swing.JButton B_cbrt;
    private javax.swing.JButton B_cos;
    private javax.swing.JButton B_div;
    private javax.swing.JButton B_dot;
    private javax.swing.JButton B_equal;
    private javax.swing.JButton B_hex;
    private javax.swing.JButton B_log;
    private javax.swing.JButton B_mul;
    private javax.swing.JButton B_octal;
    private javax.swing.JButton B_pi;
    private javax.swing.JButton B_plus;
    private javax.swing.JButton B_pow;
    private javax.swing.JButton B_sin1;
    private javax.swing.JButton B_square;
    private javax.swing.JButton B_suare3;
    private javax.swing.JButton B_sub;
    private javax.swing.JButton B_tan1;
    private javax.swing.JTextField display;
    // End of variables declaration//GEN-END:variables
}
